### ISSUE TITLE
KoIn dataset images

### ISSUE THREAD

**Issue by h6197627** [dukong1/KoIn_Benchmark_Dataset#1]
Hello,
first of all, thank you for sharing KoIn dataset!
As far as I understand, KoIn dataset upload is incomplete, for example KoIn100 train has only 55 (+1) identity folders instead of 100. Are there any plans to finish uploading?

**Comment by dukong1** [comment]
Thank you for your email, I have read it.
First of all, thank you for your interest in the KoIn dataset.
To answer your question, we are slowly re-examining the KoIn100 dataset to
see if it contains different images.
It shouldn't take long, and we'll upload them in order as we complete our
review.
Thanks again.

2023년 12월 8일 (금) 오후 7:25, h6197627 ***@***.***>님이 작성:

**Comment by h6197627** [comment]
Close due inactivity for more than half a year.

**Comment by HojunYou** [comment]
Hello, any follow-ups on this matter?

I noticed that the KoIn100 dataset currently contains only 55 identities. Are there plans to expand this dataset in the near future? Any updates on this would be greatly appreciated.

Thank you!
